### ISSUE TITLE
unmet peer dependency warning when installing plugin

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-api-plugin#31]
Installing the plugin I get an unmet peer dependency warning:

```
h plugins:install api
warning "@heroku-cli/plugin-api > @oclif/command@1.5.16" has unmet peer dependency "@oclif/plugin-help@^2".
...
```

Since:
https://github.com/oclif/command/blob/v1.5.16/package.json#L32-L35

(The plugin functions fine once installed however)

**Comment by edmorley** [comment]
I'm still seeing this:

```
$ h update
warning "@heroku-cli/plugin-api > @oclif/command@1.5.16" has unmet peer dependency "@oclif/plugin-help@^2".
Updating completions... ⣽ [4/4] Building fresh packages...
Updating completions... ⡿ [4/4] Building fresh packages...
```

**Comment by nertzy** [comment]
I was able to fix this warning by looking through the output of `heroku plugins` and seeing I had multiple copies of the API plugin installed. I removed the old version and the warnings went away.
